apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  serviceName: 
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - image: localhost:5000/streaming_fastapi_image:1.0
          name: fastapi  
          ports:
            - containerPort: 80

--- 
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000